/**
 * PF-11 D0.2 — planet-sphere pixel proof (closes handoff B4).
 *
 * Five sessions running produced "engine state is provably correct — mesh visible, scale 26,
 * camera at the documented 38-unit standoff, ultra tier, VT tiles bound — but no pixel
 * confirmation exists" (TR-079 Part 8b). Root cause found implementing this spec: on arrival the
 * camera lands at the right STANDOFF (`babylon-engine.ts`'s `travelTo`/`_beginWarp`), but nothing
 * ever re-aims its BEARING — `_tickWarp`'s idle branch always re-derives orientation from
 * `_yaw`/`_pitch`, which sit wherever free-look last left them. Every harness before this one kept
 * the camera's initial bearing, so the sphere was outside the captured frame on the programmatic
 * path AND through the real UI.
 *
 * `aimAt(bodyId)` (babylon-engine.ts) is the fix: a harness-only hook, gated behind `?testhooks`
 * so it can never become a product feature, that points `_yaw`/`_pitch` at a body's already-
 * computed world position. The render loop's existing idle-orientation tick then does the rest —
 * no new rendering path to validate, just the missing camera direction.
 *
 * CLAUDE.md #11: pixel evidence comes from `page.screenshot()` (a Locator screenshot goes through
 * the same real compositor path), never `drawImage`/`getImageData` on the canvas — the latter
 * reads back transparent on a WebGPU canvas regardless of correctness.
 */
import { test, expect, type Locator } from "@playwright/test";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import sharp from "sharp";

type EngineHandle = {
  sceneStats(): Record<string, unknown>;
  travelTo(id: string, quiet?: boolean): void;
  aimAt(id: string): boolean;
  arrivedId: string | null;
};

const readStats = (engine: Locator) =>
  engine.evaluate((el) => (el as unknown as EngineHandle).sceneStats());

const readArrivedId = (engine: Locator) =>
  engine.evaluate((el) => (el as unknown as EngineHandle).arrivedId);

/** Reference screenshots are committed once by hand, not regenerated by every CI run — a test
 * silently rewriting files under `docs/` on each pass would be its own defect. Set
 * `PF11_CAPTURE_REFERENCE=1` locally to (re)write them after a genuine visual change. */
const CAPTURE_DIR = resolve(process.cwd(), "docs/test-reports/assets");

const PLANET_BODIES = ["mars", "moon"] as const;

test.describe("Planet-sphere pixel proof (PF-11 D0.2)", () => {
  test.beforeEach(async ({ page }) => {
    // ?testhooks arms aimAt() — see its guard in babylon-engine.ts. The default engine (Babylon)
    // is under test; no ?engine= override.
    await page.goto("/?testhooks");
    await page.waitForSelector("babylon-scene");
  });

  for (const body of PLANET_BODIES) {
    test(`${body}-class arrival renders real pixels, not just correct engine state`, async ({
      page,
    }) => {
      // The default 30s test timeout is sized for lighter specs — this one boots the full
      // catalog scene AND sums three sequential polls (starSource/arrivedId/planetSphereVisible)
      // that can individually approach their own timeouts on a loaded machine (craft-ship.spec.ts
      // sets the same kind of budget for the same reason).
      test.setTimeout(60000);
      const engine = page.locator("babylon-scene");

      await expect
        .poll(async () => (await readStats(engine)).starSource, {
          timeout: 20000,
        })
        .not.toBeNull();

      await engine.evaluate(
        (el, id) => (el as unknown as EngineHandle).travelTo(id),
        body,
      );
      await expect
        .poll(() => readArrivedId(engine), { timeout: 15000 })
        .toBe(body);

      // Sphere gating (_tickPlanetSphere) keys off arrivedId and runs the same frame — visible
      // should already be true, but poll rather than assume the exact tick ordering.
      await expect
        .poll(async () => (await readStats(engine)).planetSphereVisible, {
          timeout: 10000,
        })
        .toBe(true);

      const aimed = await engine.evaluate(
        (el, id) => (el as unknown as EngineHandle).aimAt(id),
        body,
      );
      expect(aimed, "aimAt() should arm under ?testhooks").toBe(true);

      // aimAt only sets _yaw/_pitch; the render loop's idle-mode tick re-derives the camera
      // quaternion from them on its next pass. A couple of frames of margin, not a fixed guess.
      await page.waitForTimeout(200);

      const png = await page.locator("babylon-scene canvas").screenshot();
      const { data, info } = await sharp(png)
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });

      // At ARRIVE_STANDOFF=38 from a PLANET_SPHERE_RADIUS=26 sphere, the disc's angular diameter
      // is ~69° — once aimed, a centred 30% crop sits well inside the sphere, never in the
      // surrounding starfield, on any viewport this suite uses.
      const cropFrac = 0.3;
      const x0 = Math.floor(info.width * (0.5 - cropFrac / 2));
      const x1 = Math.floor(info.width * (0.5 + cropFrac / 2));
      const y0 = Math.floor(info.height * (0.5 - cropFrac / 2));
      const y1 = Math.floor(info.height * (0.5 + cropFrac / 2));

      let sum = 0;
      let sumSq = 0;
      let n = 0;
      for (let y = y0; y < y1; y++) {
        for (let x = x0; x < x1; x++) {
          const idx = (y * info.width + x) * info.channels;
          const lum =
            0.2126 * data[idx] +
            0.7152 * data[idx + 1] +
            0.0722 * data[idx + 2];
          sum += lum;
          sumSq += lum * lum;
          n++;
        }
      }
      const mean = sum / n;
      const variance = sumSq / n - mean * mean;

      // Deep space is near-black; a lit, textured sphere produces both real luminance and real
      // per-pixel variance (terrain, terminator, craters/clouds). A flat mid-grey placeholder
      // ball (the "loading" state _tickPlanetSphere falls back to) would pass the luminance floor
      // but fail the variance floor — the two together are the actual non-blank-region assertion.
      expect(mean, `${body} centre-crop mean luminance`).toBeGreaterThan(8);
      expect(
        variance,
        `${body} centre-crop luminance variance`,
      ).toBeGreaterThan(4);

      if (process.env.PF11_CAPTURE_REFERENCE) {
        mkdirSync(CAPTURE_DIR, { recursive: true });
        writeFileSync(resolve(CAPTURE_DIR, `pf11-d0.2-${body}.png`), png);
      }
    });
  }
});
